GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/61fad27656e7fe82ad082053

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Anu",
    "subscribedToChannel": "web simplified"
}